# Generated by Django 5.0.6 on 2024-06-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
    ]
